### ISSUE TITLE
Faker related issues

### ISSUE THREAD

**Issue by SOHELAHMED7** [cebe/yii2-app-api#16]
Following the docs as in README.md

Faker command fails

```sh
./yii faker
```

2 errors are caused because

1. [FakerController](https://github.com/cebe/yii2-app-api/blob/master/console/commands/FakerController.php#L22) looks for models in `common/models` directory instead of `common/models/faker`
2. we should also exclude `BaseModelFaker.php` as shown in screenshot 

![faker-2](https://user-images.githubusercontent.com/6770119/188171296-8b3cdd5e-7425-4c4c-9c83-17eb518ddb81.png)

**Comment by cebe** [comment]
fixed, thanks for reporting!
